In [15]:
import pandas as pd
import numpy as np
from pathlib import Path

import aind_session
from aind_ophys_data_access import capsule

import sys
sys.path.append('/root/capsule/code/')

import capsule_utils

# notebook dev
%load_ext autoreload
%autoreload 2
%matplotlib inline

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [2]:
saffron_data = aind_session.get_sessions(subject_id=721291)

Not authorized to access data asset ID obtained from DocDB: subject_id=721291, id_='24b98691-a5b5-4b1f-9cdb-d6fab661939a'
Not authorized to access data asset ID obtained from DocDB: subject_id=721291, id_='0803d5e1-8512-48f2-88a8-2158e1cfeb36'

In [3]:
cutoff_date = '2024-11-01'
default_mount = ['fb4b5cef-4505-4145-b8bd-e41d6863d7a9']
raw_data_date_list = []
processed_data_date_list = []
capsule_ids_list = []
commit_ids_list = []
processed_data_asset_ids_list = []
raw_data_asset_ids_list = []
num_provenence_data_assets_list = []
for data in saffron_data:
    raw_date = data.raw_data_asset.name.split('_')[2]    
    candidate_data = [da for da in data.data_assets if '_processed_' in da.name and da.name.split('_processed_')[1].split('_')[0] >= cutoff_date]
    candidate_data = [da for da in candidate_data if (da.provenance.commit is not None) and (da.provenance.capsule=='24cad997-4633-4ab3-a17d-8b0c01cad787')]
    processed_data_dates = [da.name.split('_processed_')[1].split('_')[0] for da in candidate_data]
    capsule_ids = [da.provenance.capsule for da in candidate_data]
    commit_ids = [da.provenance.commit for da in candidate_data]
    data_asset_ids = [da.id for da in candidate_data]
    raw_data_asset_ids = [np.setdiff1d(da.provenance.data_assets, default_mount)  for da in candidate_data]
    num_provenence_data_assets = [len(da.provenance.data_assets) for da in candidate_data]
    for i in range(len(candidate_data)):
        raw_data_date_list.append(raw_date)
        capsule_ids_list.append(capsule_ids[i])
        commit_ids_list.append(commit_ids[i])
        processed_data_asset_ids_list.append(data_asset_ids[i])
        processed_data_date_list.append(processed_data_dates[i])
        raw_data_asset_ids_list.append(raw_data_asset_ids[i])
        num_provenence_data_assets_list.append(num_provenence_data_assets[i])

In [4]:
saffron_da_df = pd.DataFrame({'raw_data_date': raw_data_date_list, 
                            'processed_date': processed_data_date_list,
                            'capsule_id': capsule_ids_list,
                            'commit_id': commit_ids_list,
                            'processed_data_asset_id': processed_data_asset_ids_list,
                            'raw_data_asset_id': raw_data_asset_ids_list})
saffron_da_df

,raw_data_date,processed_date,capsule_id,commit_id,processed_data_asset_id,raw_data_asset_id
0,2024-04-16,2024-11-06,24cad997-4633-4ab3-a17d-8b0c01cad787,ea95e8423c69e5617cacd25a1620f7b47d8828be,2b02bae7-abbb-4383-a8f7-5f6fc31b19e9,[1c7691f2-5d15-4c2f-a32d-27009b5abce7]
1,2024-04-16,2024-11-11,24cad997-4633-4ab3-a17d-8b0c01cad787,542c441005716d668e9bbd3d75690bc13ec4d30c,3ffc9f07-2daf-40d2-a1cc-7a7e55b38509,[86cff6d2-cc50-4b41-b4ed-55f9ecefba94]
2,2024-04-17,2024-11-06,24cad997-4633-4ab3-a17d-8b0c01cad787,ea95e8423c69e5617cacd25a1620f7b47d8828be,4251a7d8-1190-4064-8ead-d52cb9a8be4a,[76b4c367-dd11-46f6-bdbd-1b2c9f60ffa9]
3,2024-04-17,2024-11-11,24cad997-4633-4ab3-a17d-8b0c01cad787,542c441005716d668e9bbd3d75690bc13ec4d30c,1e484470-5f32-4107-be99-f71a4bf653b3,[9850e871-8def-4ffd-b4f2-8e346058d2a1]
4,2024-04-19,2024-11-06,24cad997-4633-4ab3-a17d-8b0c01cad787,ea95e8423c69e5617cacd25a1620f7b47d8828be,b13e52c4-2bf1-4d1f-bac8-6804d3019b81,[94f21415-497a-4dc3-bd33-291a1c67127d]
5,2024-04-22,2024-11-06,24cad997-4633-4ab3-a17d-8b0c01cad787,ea95e8423c69e5617cacd25a1620f7b47d8828be,6fa3d737-f6f4-4317-a20b-9ecf6252270f,[e2a394f1-acaf-45e8-8ffb-e2cb0a35df1d]
6,2024-04-22,2024-11-11,24cad997-4633-4ab3-a17d-8b0c01cad787,542c441005716d668e9bbd3d75690bc13ec4d30c,997cffc7-9e66-4cdf-99ab-ab5dd315a273,[89381772-ffe4-49d8-8a8f-d7ed3b725bdf]
7,2024-04-23,2024-11-06,24cad997-4633-4ab3-a17d-8b0c01cad787,ea95e8423c69e5617cacd25a1620f7b47d8828be,453046c2-ce92-4cd6-9282-6be86c25d1cf,[25331ba5-3531-4996-bbff-5a12e2fab271]
8,2024-04-23,2024-11-11,24cad997-4633-4ab3-a17d-8b0c01cad787,542c441005716d668e9bbd3d75690bc13ec4d30c,6b8535a4-78b8-42ce-8c00-25e692bb0011,[fe96b0d1-b9b3-44c1-a7ab-d627d591c27b]
9,2024-04-24,2024-11-06,24cad997-4633-4ab3-a17d-8b0c01cad787,ea95e8423c69e5617cacd25a1620f7b47d8828be,680d8fd1-691d-457e-8142-602ce27d7f39,[5b22e1d1-08f6-440a-8c7d-7f2581c24a5b]
10,2024-04-24,2024-11-11,24cad997-4633-4ab3-a17d-8b0c01cad787,542c441005716d668e9bbd3d75690bc13ec4d30c,43151456-5286-4155-896b-37578a67a13a,[53e3badf-5eb0-4f68-8f88-c0a3971d6037]
11,2024-04-26,2024-11-06,24cad997-4633-4ab3-a17d-8b0c01cad787,ea95e8423c69e5617cacd25a1620f7b47d8828be,4c8c8351-0708-4e35-8630-fe1de62df4c7,[aacce602-4092-4caa-ad6b-676c23db93e1]
12,2024-04-26,2024-11-11,24cad997-4633-4ab3-a17d-8b0c01cad787,542c441005716d668e9bbd3d75690bc13ec4d30c,8af4b210-14b8-48d7-877f-0c20b55cb331,[25e22cfd-e59f-4e96-b59f-aa33ae0488fa]
13,2024-04-29,2024-11-06,24cad997-4633-4ab3-a17d-8b0c01cad787,ea95e8423c69e5617cacd25a1620f7b47d8828be,2c57eb68-7c7f-42ad-aded-22ea1c5e0dac,[6d5527b0-98d5-40ee-9484-4a925f4970d6]
14,2024-04-29,2024-11-11,24cad997-4633-4ab3-a17d-8b0c01cad787,542c441005716d668e9bbd3d75690bc13ec4d30c,4747eb07-df8e-456a-bb0e-0e2c27dc2e03,[b77b6307-28d8-4600-89aa-26df44fdcf6f]
15,2024-04-30,2024-11-06,24cad997-4633-4ab3-a17d-8b0c01cad787,ea95e8423c69e5617cacd25a1620f7b47d8828be,189f6c6f-c98e-4a2d-89fc-13bfac346158,[7048a6d9-4113-49cf-bfa8-4f92ce988d0e]
16,2024-05-02,2024-11-06,24cad997-4633-4ab3-a17d-8b0c01cad787,ea95e8423c69e5617cacd25a1620f7b47d8828be,69ecc021-4bd4-4ff6-84cf-27f76d0b3d7f,[d03d47ed-5cb1-44dc-a46b-0bcd0cbd4601]
17,2024-05-06,2024-11-06,24cad997-4633-4ab3-a17d-8b0c01cad787,ea95e8423c69e5617cacd25a1620f7b47d8828be,88775065-f07c-46b3-992a-d4db9f68c658,[23781917-256d-4bc4-9629-a3474ad3f09a]
18,2024-05-06,2024-11-11,24cad997-4633-4ab3-a17d-8b0c01cad787,542c441005716d668e9bbd3d75690bc13ec4d30c,9323c6f3-b67f-4ca6-a6be-679cdc949cea,[49ce27c7-4c89-4994-8770-332aa68913c8]
19,2024-05-07,2024-11-06,24cad997-4633-4ab3-a17d-8b0c01cad787,ea95e8423c69e5617cacd25a1620f7b47d8828be,255291bf-a5ef-4a46-aedd-14bd38de9ed5,[3a59363d-fcf0-4af4-a145-a2de2de76f25]
20,2024-05-07,2024-11-11,24cad997-4633-4ab3-a17d-8b0c01cad787,542c441005716d668e9bbd3d75690bc13ec4d30c,33fd6e6a-08c3-4a01-9896-77bf846ea4e2,[aeceed3e-5bf1-46c2-8bde-da1d03e6ca45]
21,2024-05-08,2024-11-06,24cad997-4633-4ab3-a17d-8b0c01cad787,ea95e8423c69e5617cacd25a1620f7b47d8828be,513f286a-e368-40b1-b4aa-b4e25a391400,[8219dd46-a1ea-4f06-83a8-226878d6e0c9]
22,2024-05-13,2024-11-06,24cad997-4633-4ab3-a17d-8b0c01cad787,ea95e8423c69e5617cacd25a1620f7b47d8828be,2b801df0-bd0d-4cfd-8df2-a93b8a3b2277,[81b28f59-3080-4c71-9a8f-51d8742129a8]
23,2024-05-13,2024-11-11,24cad997-4633-4ab3-a17d-8b0c01cad787,542c441005716d668e9bbd3d75690bc13ec4d30c,cd263e8b-6262-4f49-9e59-8e93fdb4346c,[c8d5282d-ec20-4a53-b8d2-2de907fc2287]

In [5]:
saffron_da_df = saffron_da_df.query('commit_id=="ea95e8423c69e5617cacd25a1620f7b47d8828be"').copy()
saffron_da_df['raw_data_asset_id'] = saffron_da_df['raw_data_asset_id'].apply(lambda x: x[0])

In [8]:
# dsave saffron_data_asset_df
save_fn = Path('/root/capsule/scratch/Saffron/saffron_data_asset_df.csv')
save_fn.parent.mkdir(parents=True, exist_ok=True)
saffron_da_df.to_csv(save_fn, index=False)

In [ ]:
capsule.attach_assets(saffron_da_df.raw_data_asset_id.values)
capsule.attach_assets(saffron_da_df.processed_data_asset_id.values)

asset_id: 1c7691f2-5d15-4c2f-a32d-27009b5abce7 - mount_state:
asset_id: 76b4c367-dd11-46f6-bdbd-1b2c9f60ffa9 - mount_state:
asset_id: 94f21415-497a-4dc3-bd33-291a1c67127d - mount_state:
asset_id: e2a394f1-acaf-45e8-8ffb-e2cb0a35df1d - mount_state:
asset_id: 25331ba5-3531-4996-bbff-5a12e2fab271 - mount_state:
asset_id: 5b22e1d1-08f6-440a-8c7d-7f2581c24a5b - mount_state:
asset_id: aacce602-4092-4caa-ad6b-676c23db93e1 - mount_state:
asset_id: 6d5527b0-98d5-40ee-9484-4a925f4970d6 - mount_state:
asset_id: 7048a6d9-4113-49cf-bfa8-4f92ce988d0e - mount_state:
asset_id: d03d47ed-5cb1-44dc-a46b-0bcd0cbd4601 - mount_state:
asset_id: 23781917-256d-4bc4-9629-a3474ad3f09a - mount_state:
asset_id: 3a59363d-fcf0-4af4-a145-a2de2de76f25 - mount_state:
asset_id: 8219dd46-a1ea-4f06-83a8-226878d6e0c9 - mount_state:
asset_id: 81b28f59-3080-4c71-9a8f-51d8742129a8 - mount_state:
asset_id: 2b02bae7-abbb-4383-a8f7-5f6fc31b19e9 - mount_state: mounted
asset_id: 4251a7d8-1190-4064-8ead-d52cb9a8be4a - mount_state: mounted
asset_id: b13e52c4-2bf1-4d1f-bac8-6804d3019b81 - mount_state: mounted
asset_id: 6fa3d737-f6f4-4317-a20b-9ecf6252270f - mount_state: mounted
asset_id: 453046c2-ce92-4cd6-9282-6be86c25d1cf - mount_state: mounted
asset_id: 680d8fd1-691d-457e-8142-602ce27d7f39 - mount_state: mounted
asset_id: 4c8c8351-0708-4e35-8630-fe1de62df4c7 - mount_state: mounted
asset_id: 2c57eb68-7c7f-42ad-aded-22ea1c5e0dac - mount_state: mounted
asset_id: 189f6c6f-c98e-4a2d-89fc-13bfac346158 - mount_state: mounted
asset_id: 69ecc021-4bd4-4ff6-84cf-27f76d0b3d7f - mount_state: mounted
asset_id: 88775065-f07c-46b3-992a-d4db9f68c658 - mount_state: mounted
asset_id: 255291bf-a5ef-4a46-aedd-14bd38de9ed5 - mount_state: mounted
asset_id: 513f286a-e368-40b1-b4aa-b4e25a391400 - mount_state: mounted
asset_id: 2b801df0-bd0d-4cfd-8df2-a93b8a3b2277 - mount_state: mounted

In [16]:
saffron_session_df = capsule_utils.get_session_info(mouse_id=721291)

IndexError: index 1 is out of bounds for axis 0 with size 1

In [19]:
import glob
import json
data_dir='/root/capsule/data'
mouse_id = 721291
data_folders = [d for d in glob.glob(data_dir + '/*') if Path(d).is_dir()]
raw_paths = np.sort([d for d in data_folders if ('processed' not in d.split('/')[-1]) and
                    ('dlc-eye' not in d.split('/')[-1]) and
                    ('multiplane-ophys' in d.split('/')[-1]) and 
                    ('stimuli' not in d.split('/')[-1]) and
                    ('stim-response' not in d.split('/')[-1]) and
                    ('ROICat' not in d.split('/')[-1]) and
                    (str(mouse_id) in d.split('/')[-1])])

session_names = [d.split('/')[-1] for d in raw_paths]
session_keys = ['_'.join(sn.split('_')[1:3]) for sn in session_names]
session_inds = np.arange(len(session_names))
session_types = []
for raw_path in raw_paths:
    session_json_fn = Path(raw_path) / 'session.json'
    with open(session_json_fn) as f:
        session_json = json.load(f)
    session_types.append(session_json['session_type'])
session_info_df = pd.DataFrame({'session_name': session_names,
                            'session_key': session_keys,
                            'session_ind': session_inds,
                            'session_type': session_types,
                            'raw_path': raw_paths}) 
session_info_df.set_index('session_key', drop=True, inplace=True)

def _map_session_type_to_stimulus(x):
    if any(substring in x for substring in ('gratings', 'STAGE_0', 'STAGE_1')):
        return 'gratings'
    elif 'images_A' in x:
        return 'images_A'
    elif 'images_B' in x:
        return 'images_B'
    else:
        return 'unknown'

session_info_df['stimulus'] = session_info_df['session_type'].apply(lambda x: _map_session_type_to_stimulus(x))
image_sets = [s for s in session_info_df.stimulus.unique() if 'images' in s]

In [20]:
image_sets

['images_A']

In [21]:
session_info_df

,session_name,session_ind,session_type,raw_path,stimulus
session_key,,,,,
721291_2024-04-16,multiplane-ophys_721291_2024-04-16_08-21-40,0,TRAINING_0_gratings_autorewards_15min,/root/capsule/data/multiplane-ophys_721291_202...,gratings
721291_2024-04-17,multiplane-ophys_721291_2024-04-17_11-02-16,1,TRAINING_1_gratings,/root/capsule/data/multiplane-ophys_721291_202...,gratings
721291_2024-04-19,multiplane-ophys_721291_2024-04-19_08-17-25,2,TRAINING_1_gratings,/root/capsule/data/multiplane-ophys_721291_202...,gratings
721291_2024-04-22,multiplane-ophys_721291_2024-04-22_08-38-58,3,TRAINING_1_gratings,/root/capsule/data/multiplane-ophys_721291_202...,gratings
721291_2024-04-23,multiplane-ophys_721291_2024-04-23_08-20-25,4,TRAINING_2_gratings_flashed,/root/capsule/data/multiplane-ophys_721291_202...,gratings
721291_2024-04-24,multiplane-ophys_721291_2024-04-24_08-13-29,5,TRAINING_2_gratings_flashed,/root/capsule/data/multiplane-ophys_721291_202...,gratings
721291_2024-04-26,multiplane-ophys_721291_2024-04-26_08-05-27,6,TRAINING_3_images_A_10uL_reward,/root/capsule/data/multiplane-ophys_721291_202...,images_A
721291_2024-04-29,multiplane-ophys_721291_2024-04-29_08-28-28,7,TRAINING_3_images_A_10uL_reward,/root/capsule/data/multiplane-ophys_721291_202...,images_A
721291_2024-04-30,multiplane-ophys_721291_2024-04-30_08-46-46,8,TRAINING_3_images_A_10uL_reward,/root/capsule/data/multiplane-ophys_721291_202...,images_A
721291_2024-05-02,multiplane-ophys_721291_2024-05-02_08-57-52,9,TRAINING_4_images_A_training,/root/capsule/data/multiplane-ophys_721291_202...,images_A
721291_2024-05-06,multiplane-ophys_721291_2024-05-06_10-00-27,10,TRAINING_5_images_A_epilogue,/root/capsule/data/multiplane-ophys_721291_202...,images_A
721291_2024-05-07,multiplane-ophys_721291_2024-05-07_08-37-50,11,TRAINING_5_images_A_handoff_ready,/root/capsule/data/multiplane-ophys_721291_202...,images_A
721291_2024-05-08,multiplane-ophys_721291_2024-05-08_08-05-54,12,OPHYS_1_images_A,/root/capsule/data/multiplane-ophys_721291_202...,images_A
721291_2024-05-13,multiplane-ophys_721291_2024-05-13_08-27-23,13,OPHYS_1_images_A,/root/capsule/data/multiplane-ophys_721291_202...,images_A