In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

import aind_session
from aind_ophys_data_access import capsule

import sys
sys.path.append('/root/capsule/code/')

import capsule_utils

# notebook dev
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [3]:
# attach data
# 717824 (Chromium), 739564 (Paprika), 747107 (Ginger), 755252 (Anise)
mouse_id = 717824
mouse_sessions = aind_session.get_sessions(subject_id=mouse_id)
success, mouse_session_df = capsule_utils.get_mouse_session_df(mouse_id)
success

True

In [4]:
mouse_session_df

,raw_data_date,processed_data_date,capsule_id,commit_id,processed_data_asset_id,raw_data_asset_id,num_provenence_data_assets,pupil_data_asset_id,num_raw_data_asset_ids
0,2024-04-24,2025-02-10,40e54443-c0cd-4403-adb7-d3e4c69b88de,6048e958a3e2fa082507c52ef65498d0b8a18026,5844ac91-df6a-4db8-ba62-e330858ec7b4,3cd9af29-f1f3-4a95-a854-0dbcfff8aca1,2,e6607cfb-8c47-4df0-a23a-d58b72a6eacf,36
1,2024-04-25,2025-02-10,40e54443-c0cd-4403-adb7-d3e4c69b88de,6048e958a3e2fa082507c52ef65498d0b8a18026,d07df54c-dc25-48cb-abf8-663a8ebcc86d,1213101a-d3f0-4ee6-beed-c19d6ef2b57e,2,84341f60-2e16-4ba6-8c3d-50a797109fbc,36
2,2024-04-26,2025-02-10,40e54443-c0cd-4403-adb7-d3e4c69b88de,6048e958a3e2fa082507c52ef65498d0b8a18026,f21853b7-21ff-4111-ae5c-5c08142175d3,73a52715-c4a3-49c2-a5c2-d4464b3ebbe0,2,f292048b-f5a5-44e1-8a11-699760830888,36

In [5]:
capsule_utils.attach_mouse_data_assets(mouse_session_df)

asset_id: 3cd9af29-f1f3-4a95-a854-0dbcfff8aca1 - mount_state:
asset_id: 1213101a-d3f0-4ee6-beed-c19d6ef2b57e - mount_state:
asset_id: 73a52715-c4a3-49c2-a5c2-d4464b3ebbe0 - mount_state:
asset_id: 5844ac91-df6a-4db8-ba62-e330858ec7b4 - mount_state: mounted
asset_id: d07df54c-dc25-48cb-abf8-663a8ebcc86d - mount_state: mounted
asset_id: f21853b7-21ff-4111-ae5c-5c08142175d3 - mount_state: mounted
asset_id: e6607cfb-8c47-4df0-a23a-d58b72a6eacf - mount_state: mounted
asset_id: 84341f60-2e16-4ba6-8c3d-50a797109fbc - mount_state: mounted
asset_id: f292048b-f5a5-44e1-8a11-699760830888 - mount_state: mounted

True

In [14]:
capsule_utils.ID_NAME_MAP[mouse_id]

'Chromium'

In [7]:
session_info_df = capsule_utils.get_session_info(mouse_id)

In [8]:
session_info_df

,session_name,session_ind,session_type,raw_path,stimulus,stimulus_exposures,session_type_exposures
session_key,,,,,,,
717824_2024-04-24,multiplane-ophys_717824_2024-04-24_09-20-18,0,OPHYS_1_images_A,/root/capsule/data/multiplane-ophys_717824_202...,images_A,1,1
717824_2024-04-25,multiplane-ophys_717824_2024-04-25_09-18-21,1,OPHYS_4_images_B,/root/capsule/data/multiplane-ophys_717824_202...,images_B,1,1
717824_2024-04-26,multiplane-ophys_717824_2024-04-26_09-12-08,2,OPHYS_4_images_B,/root/capsule/data/multiplane-ophys_717824_202...,images_B,2,2

In [9]:
# design matrix

In [10]:
# response matrix

In [11]:
# Fit